[package]
name = "settlement"
version = "0.0.1"
edition = "2021"
authors = ["null-version_nova"]

[lib]
name = "rust_interop"
path = "rust-interop/src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
robusta_jni = "0.2"

[workspace]
members = ["rust-interop"]
